# Generated by Django 3.0.5 on 2020-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200430_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='item',
            field=models.CharField(default='DEFAULT ITEMS', max_length=40),
        ),
    ]
